manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v3.4.0
      import:
         name-allowlist:
          - cjson
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - hal_nordic
          - libmodem
          - littlefs
          - mbedtls
          - mcuboot
          - nrf_hw_models
          - nrfxlib
          - oberon-psa-crypto
          - picolibc
          - qcbor
          - segger
          - tf-psa-crypto
          - tinycrypt
          - trusted-firmware-m
          - zcbor
          - zephyr

    - name: pigeon
      url: https://github.com/justins-engineering/pigeon
      revision: main
      path: pigeon

  self:
    path: samples
